// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API 지원팀",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/find-my-email": {
            "get": {
                "description": "이름과 전화번호를 통해 등록된 이메일 주소 찾기",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "인증"
                ],
                "summary": "이메일 찾기",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사용자 이름",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "전화번호",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "이메일 찾기 성공",
                        "schema": {
                            "$ref": "#/definitions/models.FindMyEmailResponse"
                        }
                    },
                    "400": {
                        "description": "필수 파라미터 누락",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "일치하는 계정 없음",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "이메일과 비밀번호를 통해 사용자 로그인 처리",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "인증"
                ],
                "summary": "사용자 로그인",
                "parameters": [
                    {
                        "description": "로그인 요청 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "로그인 성공",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 또는 로그인 실패",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "인증된 사용자 로그아웃 처리",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "인증"
                ],
                "summary": "사용자 로그아웃",
                "responses": {
                    "200": {
                        "description": "로그아웃 성공",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/request-email-verification": {
            "post": {
                "description": "이메일 주소로 인증 코드 발송 요청",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "인증"
                ],
                "summary": "이메일 인증 요청",
                "parameters": [
                    {
                        "description": "이메일 인증 요청 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RequestEmailVerificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "인증 코드 발송 성공",
                        "schema": {
                            "$ref": "#/definitions/models.RequestEmailVerificationResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/reset-password": {
            "post": {
                "description": "이메일로 비밀번호 재설정 링크 발송",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "인증"
                ],
                "summary": "비밀번호 재설정 요청",
                "parameters": [
                    {
                        "description": "비밀번호 재설정 요청 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RequestPasswordResetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "재설정 이메일 발송 성공",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/reset-password/password": {
            "put": {
                "description": "재설정 토큰을 통해 새로운 비밀번호로 변경",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "인증"
                ],
                "summary": "비밀번호 재설정",
                "parameters": [
                    {
                        "description": "비밀번호 재설정 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "비밀번호 재설정 성공",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 또는 토큰 오류",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/sign-up": {
            "post": {
                "description": "새로운 사용자 계정 생성",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "인증"
                ],
                "summary": "사용자 회원가입",
                "parameters": [
                    {
                        "description": "회원가입 요청 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "회원가입 성공",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 또는 회원가입 실패",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/verify-email-account": {
            "post": {
                "description": "발송된 인증 코드를 통해 이메일 계정 인증 처리",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "인증"
                ],
                "summary": "이메일 계정 인증",
                "parameters": [
                    {
                        "description": "계정 인증 요청 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VerifyEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "계정 인증 성공",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 또는 인증 실패",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "description": "상세 오류 목록",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"필드 검증 실패\"]"
                    ]
                },
                "message": {
                    "description": "오류 메시지",
                    "type": "string",
                    "example": "요청 처리 중 오류가 발생했습니다."
                }
            }
        },
        "models.FindMyEmailResponse": {
            "type": "object",
            "properties": {
                "maskedEmail": {
                    "description": "마스킹된 이메일 주소",
                    "type": "string",
                    "example": "us***@example.com"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "사용자 이메일 주소",
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "description": "사용자 비밀번호",
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "expiresIn": {
                    "description": "토큰 만료 시간(초)",
                    "type": "integer",
                    "example": 3600
                },
                "token": {
                    "description": "JWT 인증 토큰",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "models.RequestEmailVerificationRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "인증받을 이메일 주소",
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "models.RequestEmailVerificationResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "응답 메시지",
                    "type": "string",
                    "example": "인증 코드가 이메일로 발송되었습니다."
                },
                "verificationId": {
                    "description": "인증 ID",
                    "type": "integer",
                    "example": 12345
                }
            }
        },
        "models.RequestPasswordResetRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "비밀번호를 재설정할 이메일 주소",
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "models.ResetPasswordRequest": {
            "type": "object",
            "required": [
                "newPassword",
                "token"
            ],
            "properties": {
                "newPassword": {
                    "description": "새로운 비밀번호 (8자 이상)",
                    "type": "string",
                    "minLength": 8,
                    "example": "newpass123"
                },
                "token": {
                    "description": "이메일로 받은 재설정 토큰",
                    "type": "string",
                    "example": "reset_token_abc123"
                }
            }
        },
        "models.SignUpRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "phone"
            ],
            "properties": {
                "agreedMarketingOptIn": {
                    "description": "마케팅 수신 동의",
                    "type": "boolean",
                    "example": true
                },
                "email": {
                    "description": "이메일 주소",
                    "type": "string",
                    "example": "user@example.com"
                },
                "name": {
                    "description": "사용자 이름",
                    "type": "string",
                    "example": "홍길동"
                },
                "password": {
                    "description": "비밀번호 (8자 이상)",
                    "type": "string",
                    "minLength": 8,
                    "example": "password123"
                },
                "phone": {
                    "description": "전화번호",
                    "type": "string",
                    "example": "010-1234-5678"
                }
            }
        },
        "models.VerifyEmailRequest": {
            "type": "object",
            "required": [
                "email",
                "verificationCode",
                "verificationId"
            ],
            "properties": {
                "email": {
                    "description": "인증할 이메일 주소",
                    "type": "string",
                    "example": "user@example.com"
                },
                "verificationCode": {
                    "description": "이메일로 받은 인증 코드",
                    "type": "string",
                    "example": "123456"
                },
                "verificationId": {
                    "description": "인증 요청 ID",
                    "type": "integer",
                    "example": 12345
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "인증 서비스 API",
	Description:      "사용자 인증, 회원가입, 이메일 인증, 비밀번호 재설정 기능을 제공하는 API 서비스",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
